### ISSUE TITLE
Degrees?

### ISSUE THREAD

**Issue by pedrofelipest** [peterhinch/micropython-samples#1]
How to use symbol degrees ° in ssd1306?

**Comment by peterhinch** [comment]
The ° symbol has value 176 (`ord('°')`) so you need to use `font_to_py.py` to generate the necessary extended ASCII (the -l argument). See [the docs](https://github.com/peterhinch/micropython-font-to-py/blob/master/FONT_TO_PY.md). You should then be able to print the character in the normal way.

**Comment by pedrofelipest** [comment]
Thanks @peterhinch, It worked.
