### ISSUE TITLE
[Feature Request] Support SparkFun RV-8803

### ISSUE THREAD

**Issue by BiatuAutMiahn** [peterhinch/micropython-samples#18]
Can you support the SparkFun RV-8803?

Product Page: https://www.sparkfun.com/products/16281

Thank you

**Comment by peterhinch** [comment]
It's not one I've considered: the DS3231 is highly accurate. What do you see as its advantages?

**Comment by BiatuAutMiahn** [comment]
It's the only module I could find with a qwiic connector. And they had one at my local Microcenter.

**Comment by peterhinch** [comment]
It's one I might consider in the future, but I'm busy working on display drivers for nanogui. You could ask in the forum: there may be someone else able to take this up.

**Comment by BiatuAutMiahn** [comment]
ok, thank you
