### ISSUE TITLE
encoders: Set the encoder value (no issue).

### ISSUE THREAD

**Issue by robert-hh** [peterhinch/micropython-samples#26]
Hello Peter,
could you consider to change the value() method similar to the position() method allowing to set the new value. The code would for instance:
```
    def value(self, value=None):
        if value is not None:
            self._pos = value
        return self._pos
```

**Comment by peterhinch** [comment]
Now done: it is more consistent. As a general point, scripts in this repo are samples intended for users to adapt as they see fit. Some might remove this functionality to save bytes...
