### ISSUE TITLE
encoders: disable IRQ?

### ISSUE THREAD

**Issue by robhamerling** [peterhinch/micropython-samples#33]
I wonder if it Isn't required (/ desired) to have a method in the Encoder class to disable interrupts at program termination?

**Comment by peterhinch** [comment]
Fair point. However:
 1. Most firmware applications do not terminate.
 2. These are code samples rather than complete solutions.
 3. I regard this as something the programmer would implement if the application required it.
 
As I state in the opening paragraph of the docs:

> The first part of this repo comprises assorted code ideas for MicroPython [...] Some are intended as pointers for programmers rather than being complete solutions. Egregious bugs will be fixed but I may not accept feature requests.
